apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  labels:
    k8s-app: filebeat
data:
  filebeat.yaml: |-

    filebeat.inputs:
    - type: container
      enabled: true
      #Collect /var/log/log-creator.log - log output file created by log-creator
      paths:
        - /var/log/*.log
      # Exclude helm tiller
      exclude_files: ['tiller-deploy-*']

      # To be used by Logstash for distinguishing index names while writing to elasticsearch.
      # If this option is set to true, the custom fields are stored as top-level fields in the output document instead of being grouped under a fields sub-dictionar
      fields_under_root: true
      fields:
        index_prefix: log-collector-logs

      # Enrich events with k8s, cloud metadata 
      processors:
        - add_cloud_metadata:
        - add_host_metadata:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/"
    # Send events to Logstash.
    output.logstash:
      enabled: true
      hosts: ["logstash:9600"]

    # You can set logging.level to debug to see the generated events by the running filebeat instance.
    # default = info -> [debug,info,warning,error]
    logging.level: info
    logging.to_files: false
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      # logging.to_files - range of 2 to 1024 files
      keepfiles: 7
      #0644: give read and write access to the file owner, and read access to all others.
      permissions: 0644