kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-master
  namespace: elk-ns
  labels:
      app: elasticsearch
spec:
  selector:
    app: elasticsearch
  #Headless service - serve as a pod discovery for Elastic search using related dns domain - StatefulSet Pods
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
