apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk-ns
data:
  logstash.conf: |-
      input {
        beats {
            port => "9600"
        }
      }
  
      filter {

        # Container logs are received with variable named index_prefix 
        # Since it is in json format, we can decode it via json filter plugin.
        if [index_prefix] == "log-collector-logs" {

          if [message] =~ /^\{.*\}$/ {
            json {
              source => "message"
              skip_on_invalid_json => true
            }
          }
          
        }

        # do not expose index_prefix field to kibana
        mutate {
          # @metadata is not exposed outside of Logstash by default.
          add_field => { "[@metadata][index_prefix]" => "%{index_prefix}-%{+YYYY.MM.dd}" }
          # since we added index_prefix to metadata, we no longer need ["index_prefix"] field.
          remove_field => ["index_prefix"]
        }

      }
  
      output {
        elasticsearch {
            hosts => "elasticsearch:9200"
            # This option is set to false by default - AVOID staying up to date with the template provided by Logstash - potential code break
            template_overwrite => false
            # a template is applied to Elasticsearch during Logstash’s startup if one with the name template_name does not already exist. By default, the contents of this template is the default template for logstash-%{+YYYY.MM.dd} which always matches indices based on the pattern logstash-*
            manage_template => false
            # The events will be stored in elasticsearch under previously defined index_prefix value.  
            index => "%{[@metadata][index_prefix]}"
            # Sniffing asks Elasticsearch for the list of all cluster nodes and adds them to the hosts list.
            sniffing => false
        }
      }