---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
  labels:
    app: logstash
  namespace: elk-ns
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
      namespace: elk-ns
    spec:
      hostname: logstash
      containers:
      - name: logstash
        ports:      
          - containerPort: 9600
            name: logstash
        image: docker.elastic.co/logstash/logstash:7.8.1
        volumeMounts:
        - name: logstash-config
          mountPath: /Users/Shared/log/logstash/pipeline/
        command:
        - logstash
        env:
          - name: xpack.monitoring.elasticsearch.url
            value: http://localhost:9200
          - name: xpack.monitoring.elasticsearch.hosts
            value: http://localhost:9200
      volumes:
      # Previously defined ConfigMap object.
      - name: logstash-config
        configMap:
          name: logstash-config
          items:
          - key: logstash.conf
            path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  type: NodePort
  selector:
    app: logstash
  ports:  
  - protocol: TCP
    port: 9600
    targetPort: 9600
    name: logstash
---