FROM docker.elastic.co/elasticsearch/elasticsearch:7.8.1
MAINTAINER Omri Freidenberg
ENV container docker
RUN yum -y update; yum clean all
RUN yum -y install systemd; yum install -y runc; yum install -y podman yum clean all; \
    (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ “/sys/fs/cgroup” ]
#EXPOSE a port which the container will listen on
CMD [“/usr/sbin/init”]