apiVersion: v1
kind: PersistentVolume
  # PersistentVolumes for the Elasticsearch pods - to maintain stateful applications
metadata:
  name: elk-pv-storage-00
  namespace: elk-ns
  labels:
    app: elasticsearch
    type: local
spec:
  storageClassName: local-storage
  local:
    path: /Users/Shared/log/elasticsearch/data
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: 10Gi
  # Node affinity is conceptually similar to nodeSelector -- it allows you to constrain which nodes your pod is eligible to be scheduled on, based on labels on the node.
  # kubectl get nodes --show-labels >> Will show labels related to that node - 'key' should exist for the pod to be able to schedule to that specific node.
  # This means that the pod will get scheduled only on a node that has a kubernetes.io/hostname=docker-desktop label.
  # Add labels to nodes - https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
