kind: Service
apiVersion: v1
metadata:
  #metadata (Here) describes the deployment itself. It gives a label for that actual deployment
  name: elasticsearch-master
  namespace: elk-ns
  labels:
      app: elasticsearch
spec:
  selector:
    app: elasticsearch
  #Headless service - serve as a pod discovery for Elastic search using related dns domain - StatefulSet Pods
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-search
  namespace: elk-ns
  labels:
    app: elasticsearch
spec:
  serviceName: elasticsearch # provides association with elasticsearch service.
  replicas: 1
  selector:
    #matchLabel: tells what pods the deployment will apply to.
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
      namespace: elk-ns
    spec:
      #securityContext for pods - uid 1000
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 1000m
              memory: "2Gi"
            requests:
              cpu: 500m
              memory: "1Gi"
        ports:
        - containerPort: 9200 # for REST API.
          name: rest
          protocol: TCP
        - containerPort: 9300 # for inter-node communication.
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          #Use Architecture-independent data - read only shared data amongst different architecture intenionally using the same OS and same version (maintain balance)
          mountPath: /Users/Shared/log/elasticsearch/data
        env:
          - name: cluster.name
            value: log-collector-elastic-search
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # sets a list of master-eligible nodes in the cluster - to be fed (seed) the discovery process by REST api or inter-node communications
          - name: discovery.seed_hosts
            value: "elastic-search-0.elasticsearch" #,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
          # specifies a list of master-eligible nodes that will participate in the master election process.
          # split brain - (N/2)+1 rule is used to set discovery.zen.minimum_master_nodes to avoid split brain problem and master node should be in odd number.
          - name: cluster.initial_master_nodes
            value: "elastic-search-0" #,es-cluster-1,es-cluster-2"
          # specifies heap memory - By default, Elasticsearch tells the JVM to use a heap with a minimum and maximum size of 1 GB(must be equal according to docs).
          # Xms - X minimum size
          # Xmx - X maximum size
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: xpack.monitoring.enabled
            value: "true"
          - name: xpack.monitoring.collection.enabled 
            value: "true"
          # (Open jira ticket under Elastic-Search - expose elastic to local host network for elastic - http://codingfundas.com/setting-up-elasticsearch-6-8-with-kibana-and-x-pack-security-enabled/index.html
          - name: network.host
            value: 0.0.0.0
          - name: xpack.security.enabled
            value: "false"
        #securityContext for containers - uid
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          runAsUser: 1000
      # Each init containers run to completion in the specified order.
      initContainers:
      # By default k8s mounts data directory as root, which renders it inaccessible to Elasticsearch - need to change owner. 
      - name: fix-permissions
        image: busybox
        # Octal representation for chmod - 1000 - access to file only - no folder premissions. http://www.filepermissions.com/file-permission/1000
        command: 
          - /bin/sh
          - -c 
          - |-
            chown -R 1000:1000 /Users/Shared/log/elasticsearch/data
            chmod 777 /Users/Shared/log/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /Users/Shared/log/elasticsearch/data
      # Increase virtual memory to maximum, in-order to prevent OOM errors for elastic search instance.
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      # Increase the max number of open file descriptors
      # Increase the limits on the number of files (file descriptors) a single process can have open at a time
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  # PersistentVolumes for the Elasticsearch pods - to maintain stateful applications
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: elk-ns
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      volumeMode: Filesystem
      storageClassName: local-storage
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          app: elasticsearch
